#ifndef DEFINITIONS_HPP
#define DEFINITIONS_HPP

#define SCREEN_WIDTH  768
#define SCREEN_HEIGHT 1024

#define SPLASH_STATE_SHOW_TIME 3.0
#define SPLASH_SCENE_BACKGROUND_FILEPATH "resources/res/Splash-Background.png"

#endif //DEFINITIONS_HPP